# FINAL WORKFLOW - Using Publish Profile authentication

name: Build and deploy Python app to Azure Web App - smarthealthai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'smarthealthai'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          app-settings-json: |
            [
                { "name": "GOOGLE_API_KEY", "value": "${{ secrets.GOOGLE_API_KEY }}", "slotSetting": false },
                { "name": "Maps_API_KEY", "value": "${{ secrets.Maps_API_KEY }}", "slotSetting": false }
            ]
